### ISSUE TITLE
Input lat/long instead of hardcoded location

### ISSUE THREAD

**Issue by pavelmoulisjr** [Novalys/Pokemon-Go-Rocket-API#4]
Current hardcoded location (64-65 MainForm.cs), replace with temporary lat/long input until I create a draggable map.

**Comment by Novalys** [comment]
The plan was to add Google Maps support #1 eventually, for now I hard coded that location since it's a good spot in London :smile:

**Comment by pavelmoulisjr** [comment]
Oh awkward, completely missed that. Nice, nice! 

:laughing:

**Comment by Novalys** [comment]
Duplicate of #1
